In [1]:
import pandas as pd
import numpy as np

In [2]:
from pathlib import Path

In [3]:
dPath = Path("../docs/dumps")

In [4]:
import pickle

In [5]:
with open(dPath / "train_without_running.pkl", 'rb') as filename:
    X_train,y_train = pickle.load(filename)

In [6]:
with open(dPath / "test_data.pkl", 'rb') as filename:
    test_data = pickle.load(filename)

In [7]:
with open(dPath / "retypelabels.pkl", 'rb') as filename:
    retypelabels = pickle.load(filename)

In [8]:
with open(dPath / "mutclslabels.pkl", 'rb') as filename:
    mutclslabels = pickle.load(filename)

In [9]:
mutclscodes = dict(zip(mutclslabels,range(len(mutclslabels))))

In [10]:
retypecodes = dict(zip(retypelabels,range(len(retypelabels))))

In [11]:
X_train.head()

MutatorClass  returnType  numExecuted  numTestCover  numAssertInTM  \
0            11         0.0            0             0              0   
1            11         0.0            0             0              0   
2            11         0.0            0             0              0   
3            11         0.0            0             0              0   
4             7         0.0            0             0              0   

   numAssertInTC  ppnumberOfClasses  ppnumberOfStatements  ppavcc  \
0              0                2.0                  85.0     4.0   
1              0                2.0                  85.0     4.0   
2              0                2.0                  85.0     4.0   
3              0                2.0                  85.0     4.0   
4              0                2.0                  85.0     4.0   

   pphalsteadCumulativeBugs  ...  mmhalsteadVolume  mmnumberOfOperands  \
0                  0.849073  ...        888.761992                86.0   
1                  0.849073  ...        888.761992                86.0   
2                  0.849073  ...        888.761992                86.0   
3                  0.849073  ...        888.761992                86.0   
4                  0.849073  ...        888.761992                86.0   

   mminstanceVariablesReferenced  mmlocalInstanceVariablesReferenced  \
0                            0.0                                 0.0   
1                            0.0                                 0.0   
2                            0.0                                 0.0   
3                            0.0                                 0.0   
4                            0.0                                 0.0   

   mmnumberOfVariableReferences  mmvariablesReferenced  mmnumberOfOperators  \
0                          32.0                    6.0                 81.0   
1                          32.0                    6.0                 81.0   
2                          32.0                    6.0                 81.0   
3                          32.0                    6.0                 81.0   
4                          32.0                    6.0                 81.0   

   mmmaxDepthOfNesting  mmnumberOfExpressions  mmnumberOfLoops  
0                  2.0                   27.0              4.0  
1                  2.0                   27.0              4.0  
2                  2.0                   27.0              4.0  
3                  2.0                   27.0              4.0  
4                  2.0                   27.0              4.0  

[5 rows x 95 columns]

In [12]:
X_test = test_data.drop("Detected", axis=1)

In [13]:
y_test = test_data.Detected

In [14]:
X_test['MutatorClass'] = X_test.MutatorClass.map(mutclscodes.get)

In [15]:
X_test['returnType'] = X_test.returnType.map(retypecodes.get)

In [16]:
X_test.head()

MutatorClass  returnType  numExecuted  numTestCover  numAssertInTM  \
0             5           0           32            16              2   
1             0           2            1             1              1   
2             4           2            1             1              1   
3             0           1            1             1              1   
4             4           1            1             1              1   

   numAssertInTC  ppnumberOfClasses  ppnumberOfStatements    ppavcc  \
0              2                3.0                 152.0  1.258065   
1              2                3.0                 152.0  1.258065   
2              2                3.0                 152.0  1.258065   
3              2                3.0                 152.0  1.258065   
4              2                3.0                 152.0  1.258065   

   pphalsteadCumulativeBugs  ...  mmhalsteadVolume  mmnumberOfOperands  \
0                  1.925253  ...         50.189475                 7.0   
1                  1.925253  ...         68.000000                 7.0   
2                  1.925253  ...         68.000000                 7.0   
3                  1.925253  ...         46.604513                 5.0   
4                  1.925253  ...         46.604513                 5.0   

   mminstanceVariablesReferenced  mmlocalInstanceVariablesReferenced  \
0                            0.0                                 0.0   
1                            1.0                                 0.0   
2                            1.0                                 0.0   
3                            0.0                                 0.0   
4                            0.0                                 0.0   

   mmnumberOfVariableReferences  mmvariablesReferenced  mmnumberOfOperators  \
0                           2.0                    1.0                  7.0   
1                           1.0                    1.0                 10.0   
2                           1.0                    1.0                 10.0   
3                           0.0                    0.0                  8.0   
4                           0.0                    0.0                  8.0   

   mmmaxDepthOfNesting  mmnumberOfExpressions  mmnumberOfLoops  
0                  0.0                    1.0              0.0  
1                  0.0                    1.0              0.0  
2                  0.0                    1.0              0.0  
3                  0.0                    1.0              0.0  
4                  0.0                    1.0              0.0  

[5 rows x 95 columns]

In [17]:
names = ['MutatorClass','numAssertInTC','numAssertInTM','numExecuted','numTestCover','ppavcc','pploc','ppmaintainabilityIndex','ppmaintainabilityIndexNC','ppnumberOfClasses','ppnumberOfStatements','pptcc']

In [18]:
len(names)

12

In [19]:
X_train = X_train[names]

In [20]:
X_test = X_test[names]

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rf = RandomForestClassifier(n_estimators=150, oob_score=True, random_state=42, n_jobs=-1)

In [23]:
%time rf.fit(X_train, y_train)

Wall time: 3min 11s


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=-1, oob_score=True, random_state=42, verbose=0,
                       warm_start=False)

In [24]:
from sklearn.metrics import roc_auc_score

In [25]:
def print_score(m):
    res = [m.score(X_train, y_train), m.score(X_test, y_test), roc_auc_score(y_test, m.predict(X_test))]
    if hasattr(m, 'oob_score_'): res.append(m.oob_score_)
    print(res)

In [26]:
from sklearn.metrics import classification_report
print(classification_report(y_test,  rf.predict(X_test)))

              precision    recall  f1-score   support

       False       0.63      0.21      0.31     20633
        True       0.68      0.93      0.79     37843

    accuracy                           0.68     58476
   macro avg       0.66      0.57      0.55     58476
weighted avg       0.67      0.68      0.62     58476



In [27]:
print_score(rf)

[0.9659934551743525, 0.6776968328887065, 0.5708315362625145, 0.938923479552474]


In [28]:
with open(dPath / "rf_exp_original_12_paper.pkl", 'wb') as filename:
    pickle.dump(rf,filename)

In [35]:
rf.feature_importances_

array([0.0479228 , 0.23397058, 0.14323279, 0.2227419 , 0.19119882,
       0.03035658, 0.01998102, 0.02197298, 0.02702744, 0.02126689,
       0.02000008, 0.02032811])

In [36]:
names = X_train.columns

In [37]:
feat_importances = pd.Series(rf.feature_importances_, index=names)
feat_importances.sort_values(ascending=False,inplace=True)

In [38]:
y_train.sum() / y_train.shape[0]

0.26013717509029743

In [40]:
from sklearn import metrics
metrics.roc_auc_score(y_test, rf.predict_proba(X_test)[:,1] >= 0.5)

0.5708315362625145

In [41]:
metrics.balanced_accuracy_score(y_test, rf.predict(X_test), adjusted=True)

0.1416630725250292

In [42]:
metrics.matthews_corrcoef(y_test, rf.predict(X_test))

0.21135884702968707

In [43]:
metrics.log_loss(y_test, rf.predict(X_test))

11.13218054815776

In [44]:
metrics.zero_one_loss(y_test, rf.predict(X_test))

0.3223031671112935

In [45]:
with open(dPath / "test_files.pkl", 'rb') as filename:
    test_files = pickle.load(filename)

In [46]:
li = []
for file in test_files:
    df = pd.read_csv(file)
    df = df.replace('?',np.NaN)
    df[df.columns[3:]] = df[df.columns[3:]].apply(pd.to_numeric)
    df.dropna(inplace=True)
    li.append(df)

C:\Users\Alireza\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\Alireza\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [47]:
test_data = pd.concat(li, ignore_index=True,axis=0)
test_data = test_data.reset_index(drop=True)

In [48]:
X_test = test_data.drop("Detected", axis=1)

In [49]:
X_test['MutatorClass'] = X_test.MutatorClass.map(mutclscodes.get)

In [50]:
y_test = test_data.Detected

In [51]:
X_test['returnType'] = X_test.returnType.map(retypecodes.get)

In [55]:
X_test = X_test[names]

In [56]:
from sklearn import metrics
metrics.roc_auc_score(y_test, rf.predict_proba(X_test)[:,1] >= 0.5)

0.9316122263002329

In [57]:
metrics.balanced_accuracy_score(y_test, rf.predict(X_test), adjusted=True)

0.8632244526004658

In [58]:
metrics.matthews_corrcoef(y_test, rf.predict(X_test))

0.7617662634626299

In [59]:
metrics.log_loss(y_test, rf.predict(X_test))

2.367282405829863

In [60]:
metrics.zero_one_loss(y_test, rf.predict(X_test))

0.06853847574021044

In [61]:
metrics.precision_recall_fscore_support(y_test, rf.predict(X_test))

(array([0.98848358, 0.68374927]),
 array([0.93140447, 0.93181998]),
 array([0.95909553, 0.788739  ]),
 array([238310,  37929], dtype=int64))

In [5]:
with open(dPath / "rf_exp_original_12_paper.pkl", 'rb') as filename:
    rf = pickle.load(filename)

In [6]:
rf.feature_importances_

array([0.0479228 , 0.23397058, 0.14323279, 0.2227419 , 0.19119882,
       0.03035658, 0.01998102, 0.02197298, 0.02702744, 0.02126689,
       0.02000008, 0.02032811])

In [7]:
names = ['MutatorClass','numAssertInTC','numAssertInTM','numExecuted','numTestCover','ppavcc','pploc','ppmaintainabilityIndex','ppmaintainabilityIndexNC','ppnumberOfClasses','ppnumberOfStatements','pptcc']

In [8]:
feat_importances = pd.Series(rf.feature_importances_, index=names)
feat_importances.sort_values(ascending=False,inplace=True)

In [11]:
feat_importances.to_excel(dPath / "rf_feat_importances.xlsx")